import { TABLE_ITEM_HEIGHT } from './config';

/**
 * DartTable 的 props 运行时声明（与 el-table 对齐，并含分页、行拖拽、列设置、动态高度等扩展）。
 * `defineProps` 须在 table.vue 的 script setup 顶层调用并传入本对象。
 */
export const dartTableProps = {
  data: { type: Array, default: () => [] },
  height: [Number, String],
  maxHeight: [Number, String],
  stripe: Boolean,
  border: Boolean,
  size: String,
  fit: { type: Boolean, default: true },
  showHeader: { type: Boolean, default: true },
  highlightCurrentRow: Boolean,
  currentRowKey: [Number, String],
  rowClassName: [Function, String],
  rowStyle: Function,
  cellClassName: [Function, String],
  cellStyle: [Function, Object],
  headerRowClassName: [Function, String],
  headerRowStyle: [Function, Object],
  headerCellClassName: [Function, String],
  headerCellStyle: [Function, Object],
  rowKey: [Function, String],
  emptyText: String,
  defaultExpandAll: Boolean,
  expandRowKeys: Array,
  defaultSort: Object,
  tooltipEffect: String,
  showSummary: Boolean,
  sumText: String,
  summaryMethod: Function,
  spanMethod: Function,
  selectOnIndeterminate: { type: Boolean, default: true },
  indent: { type: Number, default: 16 },
  lazy: Boolean,
  load: Function,
  treeProps: Object,
  tableLayout: String,
  scrollbarAlwaysOn: Boolean,
  showOverflowTooltip: Boolean,
  flexible: Boolean,
  loading: Boolean,
  isDrag: Boolean,
  isUseDragHandle: Boolean,
  dragHandle: { type: String, default: '.dart-icon' },
  pageSmall: Boolean,
  pageBackground: { type: Boolean, default: true },
  pageSize: { type: Number, default: 10 },
  pageTotal: Number,
  pageCount: Number,
  pagerCount: { type: Number, default: 7 },
  currentPage: { type: Number, default: 1 },
  pageLayout: { type: String, default: 'prev, pager, next, sizes, jumper' },
  pageSizes: Array,
  pagePopperClass: String,
  pagePrevText: String,
  pageNextText: String,
  pageDisabled: Boolean,
  pageHideOnSinglePage: { type: Boolean, default: false },
  columnSet: { type: Boolean, default: false },
  isDynamicHeight: { type: Boolean, default: false },
  dynamicExtraHeight: { type: Number, default: 0 },
  tooltipOptions: { type: Object, default: () => ({}) },
  // 20260607 ADD 树形表格样式开关：启用 +/- 按钮和连接线
  treeLineStyle: { type: Boolean, default: false },
  // 表格行高度，用于动态高度计算
  itemHeight: { type: Number, default: TABLE_ITEM_HEIGHT },
};
